local config = require 'thaumaturge.config'

local colorscheme = {
  main_bg = config.transparent and 'none' or '#151515',
  popup_bg = '#292929',
  floating_bg = '#383838',
  menuOptionBackground = '#282828',
  fg = '#cdaa7d',
  bg_faded = '#7d6d59',
  white = '#ffffff',
  orange = '#cf7044',
  blue = '#5b909a',
  grey_light_blue = '#bac4cf',
  bright_yellow = '#f1c84b',
  day_nine_yellow = '#FFA717',
  zerg_purple = '#9b6f8d',
  green = '#6c9a5b',
  pure_blue = '#0000ff',
  pure_cyan = '#00ffff',  
  comment_green = '#41D422',
  macro_purple = '#c586c0',
  bright_green = '#00FF33',
  cursor = "#40ff40",
  cursor_foreground = "#303030",
  cursor_line = "#111144",
  error_red = "#ff0000",
  burlywood3 = "#cdaa7d",
  gray50 = "#7f7f7f",
  olive_drab = "#6b8e23",
  builtin = "#DAB98F",
  dark_goldenrod = "#b8860b",
  
  -- Colors from Ryan Fluery 4Coder theme
  fluery_bar                   = '#000000',
  fluery_base                  = '#fcaa05',
  fluery_pop1                  = '#de8150',
  fluery_pop2                  = '#FF0000',
  fluery_back                  = '#020202',
  fluery_margin                = '#222425',
  fluery_margin_hover          = '#63523d',
  fluery_margin_active         = '#63523d',
  fluery_list_item             = '#222425',
  fluery_list_item_hover       = '#362e25',
  fluery_list_item_active      = '#63523d',
  fluery_cursor                = '#00EE00',
  fluery_at_cursor             = '#0C0C0C',
  fluery_highlight_cursor_line = '#1E1E1E',
  fluery_highlight             = '#303040',
  fluery_at_highlight          = '#FF44DD',
  fluery_mark                  = '#494949',
  fluery_text_default          = '#b99468',
  fluery_comment               = '#666666',
  fluery_keyword               = '#f0c674',
  fluery_str_constant          = '#ffa900',
  fluery_char_constant         = '#ffa900',
  fluery_int_constant          = '#ffa900',
  fluery_float_constant        = '#ffa900',
  fluery_bool_constant         = '#ffa900',
  fluery_preproc               = '#dc7575',
  fluery_include               = '#ffa900',
  fluery_special_character     = '#FF0000',
  fluery_ghost_character       = '#4E5E46',
  fluery_highlight_junk        = '#3A0000',
  fluery_highlight_white       = '#003A3A',
  fluery_paste                 = '#DDEE00',
  fluery_undo                  = '#00DDEE',
  fluery_line_numbers_back     = '#101010',
  fluery_line_numbers_text     = '#404040',

  fleury_color_syntax_crap           = '#5c4d3c',
  fleury_color_operators             = '#bd2d2d',
  fleury_color_inactive_pane_overlay = '#00000044',
  fleury_color_inactive_pane_background = '#000000',
  fleury_color_file_progress_bar     = '#634323',
  fleury_color_brace_highlight       = '#8ffff2',
  fleury_color_brace_line            = '#9ba290',
  fleury_color_brace_annotation      = '#9ba290',
  fleury_color_index_product_type    = '#edb211',
  fleury_color_index_sum_type        = '#a7eb13',
  fleury_color_index_function        = '#de451f',
  fleury_color_index_macro           = '#2895c7',
  fleury_color_index_constant        = '#6eb535',
  fleury_color_index_comment_tag     = '#ffae00',
  fleury_color_index_decl            = '#c9598a',
  fleury_color_cursor_macro          = '#de2368',
  fleury_color_cursor_power_mode     = '#efaf2f',
  fleury_color_cursor_inactive       = '#880000',
  fleury_color_plot_cycle            = '#03d3fc',
  fleury_color_token_highlight       = '#f2d357',
  fleury_color_token_minor_highlight = '#d19045',
  fleury_color_error_annotation      = '#ff0000',
  fleury_color_lego_grab             = '#efaf6f',
  fleury_color_lego_splat            = '#efaaef',
  fleury_color_comment_user_name     = '#ffdd23',

  -- Handmade Hero 4coder colours
  handmade_back = '#0C0C0C',
  handmade_margin = '#181818',
  handmade_margin_hover = '#252525',
  handmade_margin_active = '#323232',
  --handmade_list_item = {naysayer_margin, naysayer_back}',
  --handmade_list_item_hover = {naysayer_margin_hover, naysayer_margin}',
  --handmade_list_item_active = {naysayer_margin_active, naysayer_margin_active}',
  handmade_cursor = '#00EE00',
  handmade_highlight_cursor_line = '#1E1E1E',
  handmade_highlight = '#DDEE00',
  handmade_mark = '#494949',
  handmade_text_default = '#90B080',
  handmade_at_highlight = '#FF44DD',
  handmade_comment = '#2090F0',
  handmade_comment_pop = '#00A000',
  handmade_keyword = '#D08F20',
  handmade_str_constant = '#50FF30',
  handmade_char_constant = handmade_str_constant,
  handmade_int_constant = handmade_str_constant,
  handmade_float_constant = handmade_str_constant,
  handmade_bool_constant = handmade_str_constant,
  handmade_include = handmade_str_constant,
  handmade_preproc = handmade_text_default,
  handmade_special_character = '#FF0000',
  handmade_ghost_character = '#4E5E46',

  handmade_paste = '#DDEE00',

  handmade_undo = '#00DDEE',

  handmade_highlight_junk = '#3a0000',
  handmade_highlight_white = '#003a3a',

  handmade_bar = '#888888',
  handmade_bar_active = '#666666',
  handmade_base = '#000000',
  handmade_pop1 = '#3C57DC',
  handmade_pop2 = '#FF0000',

  handmade_line_numbers_back = '#101010',
  handmade_line_numbers_text = '#404040',

  -- Naysayer 4coder colours
  naysayer_back = '#062329',
  naysayer_margin = '#143234',
  naysayer_margin_hover = '#213F41',
  naysayer_margin_active = '#2E4C4E',
  --naysayer_list_item = {naysayer_margin, naysayer_back}',
  --naysayer_list_item_hover = {naysayer_margin_hover, naysayer_margin}',
  --naysayer_list_item_active = {naysayer_margin_active, naysayer_margin_active}',
  --naysayer_cursor = {'#FFFFFF, '#FFFFFF}',
  --naysayer_at_cursor = naysayer_back',
  --naysayer_highlight_cursor_line = 0x0FFFFFFF',
  naysayer_highlight = '#703419',
  -- naysayer_mark = 0x70FFFFFF',
  naysayer_text_default = '#a8c1cc',
  naysayer_at_highlight = '#CDAA7D',
  naysayer_comment = '#117965',
  -- naysayer_comment_pop = {'#00A000, '#A00000}',
  naysayer_keyword = '#FFFFFF',
  naysayer_str_constant = '#2EC09C',
  naysayer_char_constant = naysayer_str_constant,
  naysayer_int_constant = '#7ad0c6',
  naysayer_float_constant = naysayer_int_constant,
  naysayer_bool_constant = naysayer_str_constant,
  naysayer_include = naysayer_str_constant,
  naysayer_preproc = '#86E08F',
  naysayer_special_character = '#FF0000',
  naysayer_ghost_character = '#5B4D3C',

  naysayer_paste = '#FFBB00',

  naysayer_undo = '#80005D',

  naysayer_highlight_junk = '#500000',
  naysayer_highlight_white = '#003A3A',

  naysayer_bar = '#CACACA',
  naysayer_bar_active = '#A8A8A8',
  naysayer_base = '#000000',
  naysayer_pop1 = '#03CF0C',
  naysayer_pop2 = '#FF0000',

  --naysayer_back_cycle = {0x30000000, 0x15000000, 0x48000000, 0x60000000}',

  -- naysayer_text_cycle = {'#A00000, '#00A000, '#0020B0, '#A0A000}',
  naysayer_text_cycle = naysayer_text_default,

  naysayer_line_numbers_back = '#082628',
  naysayer_line_numbers_text = '#082628',
}

return colorscheme
